# Generated by Django 4.2.30 on 2026-09-25 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='placementoffer',
            name='package',
        ),
        migrations.RemoveField(
            model_name='placementoffer',
            name='role',
        ),
        migrations.RemoveField(
            model_name='placementoffer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='expertise',
        ),
        migrations.AddField(
            model_name='activity',
            name='color_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='icon_svg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='academicmodule',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentsapp.academicmodule'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentsapp.assessment'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentsapp.student'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='class_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentsapp.classschedule'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentsapp.student'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Onboarding', 'Onboarding'), ('Completed', 'Completed'), ('Dropped', 'Dropped')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
