# Generated by Django 4.2.30 on 2026-09-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0002_remove_assessment_batch_remove_notification_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='portal_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
