# Generated by Django 4.2.30 on 2026-09-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0003_appuser_portal_password_appuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
