# Generated by Django 4.2.30 on 2026-09-25 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0004_appuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='capacity',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='batch',
            name='schedule_days',
            field=models.CharField(default='Mon-Fri', max_length=50),
        ),
        migrations.AddField(
            model_name='batch',
            name='schedule_time',
            field=models.CharField(default='9:00 AM - 1:00 PM', max_length=50),
        ),
        migrations.AddField(
            model_name='batch',
            name='trainer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentsapp.appuser'),
        ),
    ]
