# Generated by Django 4.2.30 on 2026-09-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0005_batch_capacity_batch_schedule_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicmodule',
            name='compute_env',
            field=models.CharField(blank=True, default='AWS Cloud9', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='academicmodule',
            name='hands_on_labs',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='academicmodule',
            name='term_credits',
            field=models.CharField(blank=True, default='Semester 1 / 4 Cr', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='academicmodule',
            name='topics_count',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='appuser',
            name='compute_env',
            field=models.CharField(blank=True, default='AWS Cloud9', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='hands_on_labs',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='appuser',
            name='term_credits',
            field=models.CharField(blank=True, default='Semester 1 / 4 Cr', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='topics_count',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='student',
            name='compute_env',
            field=models.CharField(blank=True, default='AWS Cloud9', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hands_on_labs',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='student',
            name='term_credits',
            field=models.CharField(blank=True, default='Semester 1 / 4 Cr', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='topics_count',
            field=models.IntegerField(default=12),
        ),
    ]
