# Generated by Django 4.2.30 on 2026-09-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0006_academicmodule_compute_env_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='payment_method',
            field=models.CharField(default='UPI', max_length=50),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
