# Generated by Django 4.2.30 on 2026-09-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0007_feepayment_balance_due_feepayment_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(default='System', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_group',
            field=models.CharField(default='All Users', max_length=100),
        ),
    ]
