# Generated by Django 4.2.30 on 2026-09-28 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0009_notification_target_student_studentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mentor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentees', to='studentsapp.appuser'),
        ),
    ]
