# Generated by Django 4.2.30 on 2026-09-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0010_student_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='capacity',
            field=models.IntegerField(default=10),
        ),
    ]
