# Generated by Django 4.2.30 on 2026-09-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0011_alter_batch_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
