# Generated by Django 4.2.30 on 2026-09-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0012_student_parent_password_student_parent_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='timing',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], default='Morning', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='timing_preference',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], default='Morning', max_length=20),
        ),
    ]
