# Generated by Django 4.2.30 on 2026-09-28 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0014_classschedule_end_time_classschedule_meeting_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('week_range', models.CharField(max_length=50)),
                ('status', models.CharField(default='Not Started', max_length=20)),
                ('learning_objectives', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(default='Upcoming', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('status', models.CharField(default='Not Started', max_length=20)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='studentsapp.curriculummodule')),
            ],
        ),
        migrations.AddField(
            model_name='curriculummodule',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='studentsapp.curriculummonth'),
        ),
    ]
