# Generated by Django 4.2.30 on 2026-09-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0015_curriculummodule_curriculummonth_curriculumtopic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculummodule',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='curriculummodule',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='curriculummonth',
            name='code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='curriculummonth',
            name='duration',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='curriculummonth',
            name='hours',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='curriculummonth',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='curriculummonth',
            name='short_topic',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='curriculummonth',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='curriculummodule',
            name='status',
            field=models.CharField(default='Upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='curriculummonth',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='curriculummonth',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='curriculumtopic',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='curriculumtopic',
            name='duration',
            field=models.CharField(default='45 min', max_length=50),
        ),
        migrations.AlterField(
            model_name='curriculumtopic',
            name='status',
            field=models.CharField(default='Upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='curriculumtopic',
            name='type',
            field=models.CharField(default='Video', max_length=50),
        ),
    ]
