# Generated by Django 4.2.30 on 2026-09-29 06:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0016_curriculummodule_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='Generative AI & LLMs', max_length=200)),
                ('order', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='curriculummodule',
            name='description',
        ),
        migrations.RemoveField(
            model_name='curriculummodule',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='curriculummonth',
            name='code',
        ),
        migrations.RemoveField(
            model_name='curriculummonth',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='curriculummonth',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='curriculummonth',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='curriculummonth',
            name='short_topic',
        ),
        migrations.RemoveField(
            model_name='curriculummonth',
            name='summary',
        ),
        migrations.AlterField(
            model_name='curriculummodule',
            name='status',
            field=models.CharField(default='Not Started', max_length=20),
        ),
        migrations.AlterField(
            model_name='curriculummonth',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='curriculummonth',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='curriculumtopic',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='curriculumtopic',
            name='duration',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='curriculumtopic',
            name='status',
            field=models.CharField(default='Not Started', max_length=20),
        ),
        migrations.AlterField(
            model_name='curriculumtopic',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('duration', models.CharField(default='90 Mins', max_length=50)),
                ('class_type', models.CharField(default='Online Class', max_length=50)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='studentsapp.coursemodule')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
