# Generated by Django 4.2.30 on 2026-09-29 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0017_coursemodule_remove_curriculummodule_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='duration',
            field=models.CharField(blank=True, default='90 Mins', max_length=50),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_classes', to='studentsapp.coursemodule'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_classes', to='studentsapp.coursetopic'),
        ),
    ]
