# Generated by Django 4.2.30 on 2026-09-30 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0019_attendance_batch_alter_attendance_class_schedule_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='class_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='studentsapp.classschedule'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave'), ('Late', 'Late')], default='Present', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'class_schedule')},
        ),
    ]
