# Generated by Django 4.2.30 on 2026-09-30 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0021_alter_attendance_unique_together_task_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='direction',
            field=models.CharField(choices=[('sent', 'Sent by Mentor'), ('question', 'Student Question')], default='sent', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to='studentsapp.appuser'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_questions', to='studentsapp.student'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to='studentsapp.student'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
