# Generated by Django 4.2.30 on 2026-10-01 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0022_notification_direction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculummonth',
            options={'ordering': ['number', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_modules', to='studentsapp.curriculummonth'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='class_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='studentsapp.classschedule'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Leave', 'Leave')], default='Present', max_length=20),
        ),
        migrations.AlterField(
            model_name='curriculummonth',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='curriculummonth',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'class_schedule')},
        ),
    ]
